name: ci-cd

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Сделать Gradle Wrapper исполняемым файлом.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Собрать JAR-файл.
      - name: Build JAR
        run: ./gradlew bootJar

      # Запустить тесты.
      - name: Run tests
        run: ./gradlew check --rerun-tasks

      # Загрузить файл, чтобы сделать его доступным для последующих шагов.
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ success() }}
    steps:
      # Скачать JAR-файл.
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./artifact

      # Переименовать JAR-файл (в исходном наименовании файля
      # должны быть версии. А нам удобно всегда стартовать
      # именно конкретный файл, а не писать маску.
      - name: Rename the jar-file.
        run: mv ./artifact/*.jar ./artifact/app.jar

      # Передать файл на сервер.
      - name: Upload jar via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./artifact/*.jar"
          strip_components: 1
          target: "/root/cicd"

      # Перезапустить приложение на сервере
      # (или запустить, если не работало).
      - name: Run on server
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: systemctl restart hw.service