name: ci-cd

# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow

on: # Триггеры
  push:
    branches: ["main"] # Запускать workflow при каждом пуше в репозиторий
  pull_request:
    branches: ["main"] # Запускать workflow при создании pull request.

jobs:
  build-and-test: # Собрать и тестировать
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Использовать Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # 2. Gradlew сдеть исполняемым файлом.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 3. Собрсть JAR
      - name: Build with Gradle
        run: ./gradlew bootJar

      # 4. Запустить тесты
      - name: Run tests wалith Gradle
        id: tests
        run: ./gradlew check --rerun-tasks

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ success() }} # Только если предыдущий шаг успешен.
    steps: # Перейти в нужный каталог.
           # Выполнить pull.
           # Собрать на сервере. Иначе изменения в коде не приведут к видимому результату
           # в работе приложения.
           # Перезапустить приложение.
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH            
            cd /root/cicd 
            git pull
            ./gradlew bootJar
            sudo systemctl restart hw.service
